// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnseenWebApp.Data;

#nullable disable

namespace UnseenWebApp.Migrations
{
    [DbContext(typeof(UnseenWebAppDbContext))]
    [Migration("20250730183043_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("UnseenWebApp.Data.TopScoreUniqueStringEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAtUtc")
                        .IsDescending();

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("TopScoreUniqueStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
